name: CI master push
run-name: ${{ github.actor }} pushed to master branch. 🚀 # optional
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'enter version(x.y.z)'
        required: true
        default: v1.0.0
  push:
    branches:
      - main

env:
  VERSION: ${{ github.event.inputs.tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get service name
        run: |
          echo "SERVICE=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Upload Docker Image Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE }}:latest
          build-args: |
            NANOOGOOGAE_JWT_SECRET_KEY=${{ secrets.NANOOGOOGAE_JWT_SECRET_KEY }}
            NANOOGOOGAE_MONGODB_DATABASE=${{ secrets.NANOOGOOGAE_MONGODB_DATABASE }}
            NANOOGOOGAE_MONGODB_URI=${{ secrets.NANOOGOOGAE_MONGODB_URI }}

      - name: Upload Docker Image with Tag
        uses: docker/build-push-action@v2
        if: ${{ env.VERSION }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE }}:${{ env.VERSION }}

      - name: Deploy
        run: |
          echo "Deploy"